name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-gradle:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: ['17', '21']
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          # cache-dependency-path: |
          #   ./**/*.gradle.kts
          #   ./gradle/wrapper/gradle-wrapper.properties
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Test
        run: ./gradlew check -i --no-daemon
      - name: Upload Results
        uses: actions/upload-artifact@v4
        if: always() # This ensures that test results are uploaded even if the test step fails
        with:
          name: test-results
          path: |
            **/build/reports/
            **/build/test-results/

#  test-sbt:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDK 21
#        uses: actions/setup-java@v4
#        with:
#          cache: 'sbt'
#          java-version: 21
#          distribution: 'temurin'
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v3
#      - name: Setup sbt
#        uses: sbt/setup-sbt@v1
#      - name: Build and test
#        run: sbt -v publishLocalGradleDependencies ++test
#        working-directory: ./tasks-scala
#
#  publish-snapshot:
#    runs-on: ubuntu-latest
#    needs: test
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: 11
#          distribution: 'temurin'
#      - name: Publish Snapshot
#        run: ./gradlew publish --no-daemon -i
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
