name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: ['17', '21']
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          # cache-dependency-path: |
          #   ./**/*.gradle.kts
          #   ./gradle/wrapper/gradle-wrapper.properties
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Test
        run: ./gradlew check --no-daemon
      - name: Upload Results
        uses: actions/upload-artifact@v3
        if: always() # This ensures that test results are uploaded even if the test step fails
        with:
          name: test-results
          path: |
            **/build/reports/
            **/build/test-results/

  publish-snapshot:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Publish Snapshot
        run: ./gradlew publish --no-daemon -i
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
